[package]
name = "os-virtual-input"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-engine = { path = "../core-engine" }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { version = "0.25", features = ["highsierra"] }

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13"

[lib]
name = "os_virtual_input"
path = "src/lib.rs"
