[package]
name = "daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-engine = { path = "../core-engine" }
ctrlc = "3.5.2"
hid-capture = { path = "../hid-capture" }
os-virtual-input = { path = "../os-virtual-input" }
serde_json = "1"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13"

[dev-dependencies]
ctrlc = "3"
